# Generated by Django 5.0.6 on 2025-03-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название статьи')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название статьи')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('img', models.ImageField(upload_to='product_img/', verbose_name='Главное фото')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Текст 1')),
                ('text_1_ru', models.TextField(blank=True, null=True, verbose_name='Текст 1')),
                ('text_1_en', models.TextField(blank=True, null=True, verbose_name='Текст 1')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Текст 2')),
                ('text_2_ru', models.TextField(blank=True, null=True, verbose_name='Текст 2')),
                ('text_2_en', models.TextField(blank=True, null=True, verbose_name='Текст 2')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Фото к статье')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Фото к статье')),
                ('text_3', models.TextField(blank=True, null=True, verbose_name='Текст 3')),
                ('text_3_ru', models.TextField(blank=True, null=True, verbose_name='Текст 3')),
                ('text_3_en', models.TextField(blank=True, null=True, verbose_name='Текст 3')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Our_mission', models.TextField(verbose_name='Наша миссия')),
                ('Our_mission_ru', models.TextField(null=True, verbose_name='Наша миссия')),
                ('Our_mission_en', models.TextField(null=True, verbose_name='Наша миссия')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('number_phone_1', models.BigIntegerField(verbose_name='Номер телефона 1')),
                ('number_phone_2', models.BigIntegerField(verbose_name='Номер телефона 2')),
                ('email', models.CharField(max_length=200, verbose_name='Электронная почта')),
                ('id_group', models.BigIntegerField(verbose_name='id Group')),
            ],
            options={
                'verbose_name': 'Основную информацию',
                'verbose_name_plural': 'Основная информация',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.BooleanField(verbose_name='Товар по скидке')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='Цена по скидке')),
                ('img', models.ImageField(upload_to='product_img/', verbose_name='Фото')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('full_description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('full_description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('available', models.BooleanField(verbose_name='Наличие')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина в см.')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота в см.')),
                ('quality_checking', models.BooleanField(verbose_name='Проверка качества')),
                ('guarantee', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гарантия')),
                ('guarantee_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гарантия')),
                ('guarantee_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гарантия')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Guest_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('tel_number', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_public', models.BooleanField(verbose_name='Публиковать')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'гостевой Отзыв',
                'verbose_name_plural': 'гостевые Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('stars', models.IntegerField(verbose_name='Рейтинг')),
                ('is_public', models.BooleanField(verbose_name='Публиковать')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
